fill Flight+FlightsInfo+FlightStore
yanna-stepanova/Airport pull request #1
Opened 2020-04-21 18:16 UTC by yanna-stepanova

Check it, please! Because I can't figure out how to join FlightStore and FlightsInfo

2020-04-22 11:51 UTC, yanna-stepanova commented
This version is better than previous :) I hope...

2020-04-22 14:54 UTC, OleksandrLarin requested changes

2020-04-22 14:54 UTC, OleksandrLarin commented on src/main/java/info/InfoCenterServiceImpl.java
> +    private TerminalService terminal = new TerminalServiceImpl();
Нам не нужно тут инициализировать TerminalService мы его получаем через конструктор

2020-04-22 14:54 UTC, OleksandrLarin commented on src/main/java/info/InfoCenterServiceImpl.java
> +        flightsInfo = new FlightsInfo(terminal.getAllFlights());
нам не нужно здесь создавать FlightsInfo его лучше создать сразу в меотде getAllFlights()

2020-04-22 14:54 UTC, OleksandrLarin commented on src/main/java/info/InfoCenterServiceImpl.java
> +    private FlightsInfo flightsInfo;
Лучше обойтись без этого поля

2020-04-22 14:54 UTC, OleksandrLarin commented on src/main/java/info/InfoCenterServiceImpl.java
> +        return flightsFrom;
не хорошо возвращать null

2020-04-22 14:54 UTC, OleksandrLarin commented on src/main/java/model/FlightsInfo.java
> +    private Set<Flight> flightsInfo = new HashSet<>();  // рейсы для которых будет отображаться информация
Создавать HashSet лучше в конструкторе

2020-04-22 14:54 UTC, OleksandrLarin commented on src/main/java/store/FlightStore.java
> +        return flightStore;
нужно возвращать не список, а его копию, например так:  `return new ArrayList<Flight>(flightStore);`

2020-04-22 14:54 UTC, OleksandrLarin commented on src/main/java/terminal/TerminalServiceImpl.java
> +    private Set<Flight> terminalSet = new HashSet<>();
Идея TerminalService в том что он использует внутри себя FlightStore и все операции поиск/удаление/добавление производит непосредственно с FlightStore

2020-04-23 21:44 UTC, yanna-stepanova commented on src/main/java/info/InfoCenterServiceImpl.java
> +    private TerminalService terminal = new TerminalServiceImpl();
Переделала, но не уверена

2020-04-23 21:44 UTC, yanna-stepanova commented on src/main/java/info/InfoCenterServiceImpl.java
> +        flightsInfo = new FlightsInfo(terminal.getAllFlights());
done

2020-04-23 21:45 UTC, yanna-stepanova commented on src/main/java/info/InfoCenterServiceImpl.java
> +    private FlightsInfo flightsInfo;
done

2020-04-23 21:46 UTC, yanna-stepanova commented on src/main/java/model/FlightsInfo.java
> +    private Set<Flight> flightsInfo = new HashSet<>();  // рейсы для которых будет отображаться информация
done

2020-04-23 21:47 UTC, yanna-stepanova commented on src/main/java/terminal/TerminalServiceImpl.java
> +    private Set<Flight> terminalSet = new HashSet<>();
done....maybe

2020-04-23 21:49 UTC, yanna-stepanova commented on src/main/java/store/FlightStore.java
> +        return flightStore;
done

2020-04-25 09:44 UTC, OleksandrLarin requested changes
Резолвать комменты должен тот кто их писал. Это общий подход, так всегда делают. То есть когда я пишу комментарий, ты его фиксишь а я после проверки буду резолвать

2020-04-25 09:44 UTC, OleksandrLarin commented on src/main/java/Application.java
> +        flightsSet.add(new Flight(301, "Kiev", "Vienna"));
Используй константы из класса 'store.Cities.java` вместо "Kiev" и тд

2020-04-25 09:44 UTC, OleksandrLarin commented on src/main/java/terminal/TerminalServiceImpl.java
> +            }
```suggestion
            return FlightStore.deleteFromStore(flightNo));
```

2020-04-25 16:49 UTC, yanna-stepanova commented on src/main/java/info/InfoCenterServiceImpl.java
> +        return flightsFrom;
переделала, но верно ли?

2020-04-25 16:50 UTC, yanna-stepanova commented on src/main/java/Application.java
> +        flightsSet.add(new Flight(301, "Kiev", "Vienna"));
done

2020-04-25 16:50 UTC, yanna-stepanova commented on src/main/java/terminal/TerminalServiceImpl.java
> +            }
done

2020-05-06 16:13 UTC, OleksandrLarin commented on src/main/java/info/InfoCenterServiceImpl.java
> +        return flightsFrom;
```suggestion
        return new FlightsInfo(terminal.getFlightByDeparture(departure));
```

2020-05-08 19:12 UTC, merged